//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/ciern/RiderProjects/ANTLR_DP/AntlrDP/AntlrDP/AntlrDP/SequenceDiagram.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SequenceDiagramParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISequenceDiagramVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJson([NotNull] SequenceDiagramParser.JsonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObj([NotNull] SequenceDiagramParser.ObjContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] SequenceDiagramParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.arr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArr([NotNull] SequenceDiagramParser.ArrContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] SequenceDiagramParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] SequenceDiagramParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.xmiId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmiId([NotNull] SequenceDiagramParser.XmiIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.xmiIdRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmiIdRef([NotNull] SequenceDiagramParser.XmiIdRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.lifeline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLifeline([NotNull] SequenceDiagramParser.LifelineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessage([NotNull] SequenceDiagramParser.MessageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.occurenceSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOccurenceSpecification([NotNull] SequenceDiagramParser.OccurenceSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.combinedFragment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCombinedFragment([NotNull] SequenceDiagramParser.CombinedFragmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.interactionOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteractionOperand([NotNull] SequenceDiagramParser.InteractionOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.guard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuard([NotNull] SequenceDiagramParser.GuardContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.fragments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFragments([NotNull] SequenceDiagramParser.FragmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecification([NotNull] SequenceDiagramParser.SpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.interactionConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteractionConstraint([NotNull] SequenceDiagramParser.InteractionConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.opaqueExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpaqueExpression([NotNull] SequenceDiagramParser.OpaqueExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.covered"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCovered([NotNull] SequenceDiagramParser.CoveredContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.receiveEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReceiveEvent([NotNull] SequenceDiagramParser.ReceiveEventContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.sendEvent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSendEvent([NotNull] SequenceDiagramParser.SendEventContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] SequenceDiagramParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.interactionOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteractionOperator([NotNull] SequenceDiagramParser.InteractionOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.operand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperand([NotNull] SequenceDiagramParser.OperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SequenceDiagramParser.ownedElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOwnedElements([NotNull] SequenceDiagramParser.OwnedElementsContext context);
}
