//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/ciern/RiderProjects/ANTLR_DP/AntlrDP/AntlrDP/AntlrDP/SequenceDiagram.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class SequenceDiagramParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, STRING=30, NUMBER=31, 
		WS=32;
	public const int
		RULE_json = 0, RULE_obj = 1, RULE_pair = 2, RULE_arr = 3, RULE_value = 4, 
		RULE_name = 5, RULE_xmiId = 6, RULE_xmiIdRef = 7, RULE_lifeline = 8, RULE_message = 9, 
		RULE_occurenceSpecification = 10, RULE_combinedFragment = 11, RULE_interactionOperand = 12, 
		RULE_guard = 13, RULE_fragments = 14, RULE_specification = 15, RULE_interactionConstraint = 16, 
		RULE_opaqueExpression = 17, RULE_covered = 18, RULE_receiveEvent = 19, 
		RULE_sendEvent = 20, RULE_body = 21, RULE_interactionOperator = 22, RULE_operand = 23, 
		RULE_ownedElements = 24;
	public static readonly string[] ruleNames = {
		"json", "obj", "pair", "arr", "value", "name", "xmiId", "xmiIdRef", "lifeline", 
		"message", "occurenceSpecification", "combinedFragment", "interactionOperand", 
		"guard", "fragments", "specification", "interactionConstraint", "opaqueExpression", 
		"covered", "receiveEvent", "sendEvent", "body", "interactionOperator", 
		"operand", "ownedElements"
	};

	private static readonly string[] _LiteralNames = {
		null, "'{'", "','", "'}'", "':'", "'['", "']'", "'true'", "'false'", "'null'", 
		"'\"name\"'", "'\"XmiId\"'", "'\"XmiIdRef\"'", "'\"uml:Lifeline\"'", "'\"uml:Message\"'", 
		"'\"uml:OccurrenceSpecification\"'", "'\"uml:CombinedFragment\"'", "'\"uml:InteractionOperand\"'", 
		"'\"guard\"'", "'\"fragment\"'", "'\"specification\"'", "'\"uml:InteractionConstraint\"'", 
		"'\"uml:OpaqueExpression\"'", "'\"covered\"'", "'\"receiveEvent\"'", "'\"sendEvent\"'", 
		"'\"body\"'", "'\"interactionOperator\"'", "'\"operand\"'", "'\"ownedElement\"'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, "STRING", "NUMBER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SequenceDiagram.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SequenceDiagramParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SequenceDiagramParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SequenceDiagramParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class JsonContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(SequenceDiagramParser.Eof, 0); }
		public JsonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_json; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJson(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonContext json() {
		JsonContext _localctx = new JsonContext(Context, State);
		EnterRule(_localctx, 0, RULE_json);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			value();
			State = 51;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ObjContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_obj; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObj(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjContext obj() {
		ObjContext _localctx = new ObjContext(Context, State);
		EnterRule(_localctx, 2, RULE_obj);
		int _la;
		try {
			State = 66;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 53;
				Match(T__0);
				State = 54;
				pair();
				State = 59;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__1) {
					{
					{
					State = 55;
					Match(T__1);
					State = 56;
					pair();
					}
					}
					State = 61;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 62;
				Match(T__2);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 64;
				Match(T__0);
				State = 65;
				Match(T__2);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LifelineContext lifeline() {
			return GetRuleContext<LifelineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public XmiIdContext xmiId() {
			return GetRuleContext<XmiIdContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public XmiIdRefContext xmiIdRef() {
			return GetRuleContext<XmiIdRefContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MessageContext message() {
			return GetRuleContext<MessageContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OccurenceSpecificationContext occurenceSpecification() {
			return GetRuleContext<OccurenceSpecificationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CoveredContext covered() {
			return GetRuleContext<CoveredContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReceiveEventContext receiveEvent() {
			return GetRuleContext<ReceiveEventContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SendEventContext sendEvent() {
			return GetRuleContext<SendEventContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CombinedFragmentContext combinedFragment() {
			return GetRuleContext<CombinedFragmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InteractionOperatorContext interactionOperator() {
			return GetRuleContext<InteractionOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InteractionOperandContext interactionOperand() {
			return GetRuleContext<InteractionOperandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public GuardContext guard() {
			return GetRuleContext<GuardContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InteractionConstraintContext interactionConstraint() {
			return GetRuleContext<InteractionConstraintContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SpecificationContext specification() {
			return GetRuleContext<SpecificationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OpaqueExpressionContext opaqueExpression() {
			return GetRuleContext<OpaqueExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperandContext operand() {
			return GetRuleContext<OperandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FragmentsContext fragments() {
			return GetRuleContext<FragmentsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BodyContext body() {
			return GetRuleContext<BodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OwnedElementsContext ownedElements() {
			return GetRuleContext<OwnedElementsContext>(0);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPair(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 4, RULE_pair);
		try {
			State = 91;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68;
				Match(STRING);
				State = 69;
				Match(T__3);
				State = 70;
				value();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 71;
				name();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 72;
				lifeline();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 73;
				xmiId();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 74;
				xmiIdRef();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 75;
				message();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 76;
				occurenceSpecification();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 77;
				covered();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 78;
				receiveEvent();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 79;
				sendEvent();
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 80;
				combinedFragment();
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 81;
				interactionOperator();
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 82;
				interactionOperand();
				}
				break;
			case 14:
				EnterOuterAlt(_localctx, 14);
				{
				State = 83;
				guard();
				}
				break;
			case 15:
				EnterOuterAlt(_localctx, 15);
				{
				State = 84;
				interactionConstraint();
				}
				break;
			case 16:
				EnterOuterAlt(_localctx, 16);
				{
				State = 85;
				specification();
				}
				break;
			case 17:
				EnterOuterAlt(_localctx, 17);
				{
				State = 86;
				opaqueExpression();
				}
				break;
			case 18:
				EnterOuterAlt(_localctx, 18);
				{
				State = 87;
				operand();
				}
				break;
			case 19:
				EnterOuterAlt(_localctx, 19);
				{
				State = 88;
				fragments();
				}
				break;
			case 20:
				EnterOuterAlt(_localctx, 20);
				{
				State = 89;
				body();
				}
				break;
			case 21:
				EnterOuterAlt(_localctx, 21);
				{
				State = 90;
				ownedElements();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public ArrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrContext arr() {
		ArrContext _localctx = new ArrContext(Context, State);
		EnterRule(_localctx, 6, RULE_arr);
		int _la;
		try {
			State = 106;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 93;
				Match(T__4);
				State = 94;
				value();
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__1) {
					{
					{
					State = 95;
					Match(T__1);
					State = 96;
					value();
					}
					}
					State = 101;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 102;
				Match(T__5);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 104;
				Match(T__4);
				State = 105;
				Match(T__5);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(SequenceDiagramParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjContext obj() {
			return GetRuleContext<ObjContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrContext arr() {
			return GetRuleContext<ArrContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 8, RULE_value);
		try {
			State = 115;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
				EnterOuterAlt(_localctx, 1);
				{
				State = 108;
				Match(STRING);
				}
				break;
			case NUMBER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 109;
				Match(NUMBER);
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 3);
				{
				State = 110;
				obj();
				}
				break;
			case T__4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 111;
				arr();
				}
				break;
			case T__6:
				EnterOuterAlt(_localctx, 5);
				{
				State = 112;
				Match(T__6);
				}
				break;
			case T__7:
				EnterOuterAlt(_localctx, 6);
				{
				State = 113;
				Match(T__7);
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 7);
				{
				State = 114;
				Match(T__8);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		NameContext _localctx = new NameContext(Context, State);
		EnterRule(_localctx, 10, RULE_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117;
			Match(T__9);
			State = 118;
			Match(T__3);
			State = 119;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class XmiIdContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public XmiIdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_xmiId; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitXmiId(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public XmiIdContext xmiId() {
		XmiIdContext _localctx = new XmiIdContext(Context, State);
		EnterRule(_localctx, 12, RULE_xmiId);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121;
			Match(T__10);
			State = 122;
			Match(T__3);
			State = 123;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class XmiIdRefContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public XmiIdRefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_xmiIdRef; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitXmiIdRef(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public XmiIdRefContext xmiIdRef() {
		XmiIdRefContext _localctx = new XmiIdRefContext(Context, State);
		EnterRule(_localctx, 14, RULE_xmiIdRef);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			Match(T__11);
			State = 126;
			Match(T__3);
			State = 127;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LifelineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		public LifelineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lifeline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLifeline(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LifelineContext lifeline() {
		LifelineContext _localctx = new LifelineContext(Context, State);
		EnterRule(_localctx, 16, RULE_lifeline);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			Match(STRING);
			State = 130;
			Match(T__3);
			State = 131;
			Match(T__12);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MessageContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		public MessageContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_message; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMessage(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MessageContext message() {
		MessageContext _localctx = new MessageContext(Context, State);
		EnterRule(_localctx, 18, RULE_message);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			Match(STRING);
			State = 134;
			Match(T__3);
			State = 135;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OccurenceSpecificationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		public OccurenceSpecificationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_occurenceSpecification; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOccurenceSpecification(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OccurenceSpecificationContext occurenceSpecification() {
		OccurenceSpecificationContext _localctx = new OccurenceSpecificationContext(Context, State);
		EnterRule(_localctx, 20, RULE_occurenceSpecification);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			Match(STRING);
			State = 138;
			Match(T__3);
			State = 139;
			Match(T__14);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CombinedFragmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		public CombinedFragmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_combinedFragment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCombinedFragment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CombinedFragmentContext combinedFragment() {
		CombinedFragmentContext _localctx = new CombinedFragmentContext(Context, State);
		EnterRule(_localctx, 22, RULE_combinedFragment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141;
			Match(STRING);
			State = 142;
			Match(T__3);
			State = 143;
			Match(T__15);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InteractionOperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		public InteractionOperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interactionOperand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInteractionOperand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InteractionOperandContext interactionOperand() {
		InteractionOperandContext _localctx = new InteractionOperandContext(Context, State);
		EnterRule(_localctx, 24, RULE_interactionOperand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145;
			Match(STRING);
			State = 146;
			Match(T__3);
			State = 147;
			Match(T__16);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GuardContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public GuardContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_guard; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGuard(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GuardContext guard() {
		GuardContext _localctx = new GuardContext(Context, State);
		EnterRule(_localctx, 26, RULE_guard);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 149;
			Match(T__17);
			State = 150;
			Match(T__3);
			State = 151;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FragmentsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public FragmentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_fragments; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFragments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FragmentsContext fragments() {
		FragmentsContext _localctx = new FragmentsContext(Context, State);
		EnterRule(_localctx, 28, RULE_fragments);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			Match(T__18);
			State = 154;
			Match(T__3);
			State = 155;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SpecificationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public SpecificationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_specification; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSpecification(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SpecificationContext specification() {
		SpecificationContext _localctx = new SpecificationContext(Context, State);
		EnterRule(_localctx, 30, RULE_specification);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 157;
			Match(T__19);
			State = 158;
			Match(T__3);
			State = 159;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InteractionConstraintContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		public InteractionConstraintContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interactionConstraint; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInteractionConstraint(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InteractionConstraintContext interactionConstraint() {
		InteractionConstraintContext _localctx = new InteractionConstraintContext(Context, State);
		EnterRule(_localctx, 32, RULE_interactionConstraint);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 161;
			Match(STRING);
			State = 162;
			Match(T__3);
			State = 163;
			Match(T__20);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpaqueExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(SequenceDiagramParser.STRING, 0); }
		public OpaqueExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_opaqueExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOpaqueExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpaqueExpressionContext opaqueExpression() {
		OpaqueExpressionContext _localctx = new OpaqueExpressionContext(Context, State);
		EnterRule(_localctx, 34, RULE_opaqueExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 165;
			Match(STRING);
			State = 166;
			Match(T__3);
			State = 167;
			Match(T__21);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CoveredContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public CoveredContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_covered; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCovered(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CoveredContext covered() {
		CoveredContext _localctx = new CoveredContext(Context, State);
		EnterRule(_localctx, 36, RULE_covered);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			Match(T__22);
			State = 170;
			Match(T__3);
			State = 171;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReceiveEventContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ReceiveEventContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_receiveEvent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReceiveEvent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReceiveEventContext receiveEvent() {
		ReceiveEventContext _localctx = new ReceiveEventContext(Context, State);
		EnterRule(_localctx, 38, RULE_receiveEvent);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			Match(T__23);
			State = 174;
			Match(T__3);
			State = 175;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SendEventContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public SendEventContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sendEvent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSendEvent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SendEventContext sendEvent() {
		SendEventContext _localctx = new SendEventContext(Context, State);
		EnterRule(_localctx, 40, RULE_sendEvent);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 177;
			Match(T__24);
			State = 178;
			Match(T__3);
			State = 179;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public BodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_body; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BodyContext body() {
		BodyContext _localctx = new BodyContext(Context, State);
		EnterRule(_localctx, 42, RULE_body);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181;
			Match(T__25);
			State = 182;
			Match(T__3);
			State = 183;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InteractionOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public InteractionOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interactionOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInteractionOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InteractionOperatorContext interactionOperator() {
		InteractionOperatorContext _localctx = new InteractionOperatorContext(Context, State);
		EnterRule(_localctx, 44, RULE_interactionOperator);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			Match(T__26);
			State = 186;
			Match(T__3);
			State = 187;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public OperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperandContext operand() {
		OperandContext _localctx = new OperandContext(Context, State);
		EnterRule(_localctx, 46, RULE_operand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189;
			Match(T__27);
			State = 190;
			Match(T__3);
			State = 191;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OwnedElementsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public OwnedElementsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ownedElements; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISequenceDiagramVisitor<TResult> typedVisitor = visitor as ISequenceDiagramVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOwnedElements(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OwnedElementsContext ownedElements() {
		OwnedElementsContext _localctx = new OwnedElementsContext(Context, State);
		EnterRule(_localctx, 48, RULE_ownedElements);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			Match(T__28);
			State = 194;
			Match(T__3);
			State = 195;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,32,198,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,1,0,1,0,1,0,1,1,1,1,1,1,1,1,5,1,58,8,1,10,
		1,12,1,61,9,1,1,1,1,1,1,1,1,1,3,1,67,8,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,
		2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,92,8,
		2,1,3,1,3,1,3,1,3,5,3,98,8,3,10,3,12,3,101,9,3,1,3,1,3,1,3,1,3,3,3,107,
		8,3,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,116,8,4,1,5,1,5,1,5,1,5,1,6,1,6,1,
		6,1,6,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,
		10,1,11,1,11,1,11,1,11,1,12,1,12,1,12,1,12,1,13,1,13,1,13,1,13,1,14,1,
		14,1,14,1,14,1,15,1,15,1,15,1,15,1,16,1,16,1,16,1,16,1,17,1,17,1,17,1,
		17,1,18,1,18,1,18,1,18,1,19,1,19,1,19,1,19,1,20,1,20,1,20,1,20,1,21,1,
		21,1,21,1,21,1,22,1,22,1,22,1,22,1,23,1,23,1,23,1,23,1,24,1,24,1,24,1,
		24,1,24,0,0,25,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		40,42,44,46,48,0,0,202,0,50,1,0,0,0,2,66,1,0,0,0,4,91,1,0,0,0,6,106,1,
		0,0,0,8,115,1,0,0,0,10,117,1,0,0,0,12,121,1,0,0,0,14,125,1,0,0,0,16,129,
		1,0,0,0,18,133,1,0,0,0,20,137,1,0,0,0,22,141,1,0,0,0,24,145,1,0,0,0,26,
		149,1,0,0,0,28,153,1,0,0,0,30,157,1,0,0,0,32,161,1,0,0,0,34,165,1,0,0,
		0,36,169,1,0,0,0,38,173,1,0,0,0,40,177,1,0,0,0,42,181,1,0,0,0,44,185,1,
		0,0,0,46,189,1,0,0,0,48,193,1,0,0,0,50,51,3,8,4,0,51,52,5,0,0,1,52,1,1,
		0,0,0,53,54,5,1,0,0,54,59,3,4,2,0,55,56,5,2,0,0,56,58,3,4,2,0,57,55,1,
		0,0,0,58,61,1,0,0,0,59,57,1,0,0,0,59,60,1,0,0,0,60,62,1,0,0,0,61,59,1,
		0,0,0,62,63,5,3,0,0,63,67,1,0,0,0,64,65,5,1,0,0,65,67,5,3,0,0,66,53,1,
		0,0,0,66,64,1,0,0,0,67,3,1,0,0,0,68,69,5,30,0,0,69,70,5,4,0,0,70,92,3,
		8,4,0,71,92,3,10,5,0,72,92,3,16,8,0,73,92,3,12,6,0,74,92,3,14,7,0,75,92,
		3,18,9,0,76,92,3,20,10,0,77,92,3,36,18,0,78,92,3,38,19,0,79,92,3,40,20,
		0,80,92,3,22,11,0,81,92,3,44,22,0,82,92,3,24,12,0,83,92,3,26,13,0,84,92,
		3,32,16,0,85,92,3,30,15,0,86,92,3,34,17,0,87,92,3,46,23,0,88,92,3,28,14,
		0,89,92,3,42,21,0,90,92,3,48,24,0,91,68,1,0,0,0,91,71,1,0,0,0,91,72,1,
		0,0,0,91,73,1,0,0,0,91,74,1,0,0,0,91,75,1,0,0,0,91,76,1,0,0,0,91,77,1,
		0,0,0,91,78,1,0,0,0,91,79,1,0,0,0,91,80,1,0,0,0,91,81,1,0,0,0,91,82,1,
		0,0,0,91,83,1,0,0,0,91,84,1,0,0,0,91,85,1,0,0,0,91,86,1,0,0,0,91,87,1,
		0,0,0,91,88,1,0,0,0,91,89,1,0,0,0,91,90,1,0,0,0,92,5,1,0,0,0,93,94,5,5,
		0,0,94,99,3,8,4,0,95,96,5,2,0,0,96,98,3,8,4,0,97,95,1,0,0,0,98,101,1,0,
		0,0,99,97,1,0,0,0,99,100,1,0,0,0,100,102,1,0,0,0,101,99,1,0,0,0,102,103,
		5,6,0,0,103,107,1,0,0,0,104,105,5,5,0,0,105,107,5,6,0,0,106,93,1,0,0,0,
		106,104,1,0,0,0,107,7,1,0,0,0,108,116,5,30,0,0,109,116,5,31,0,0,110,116,
		3,2,1,0,111,116,3,6,3,0,112,116,5,7,0,0,113,116,5,8,0,0,114,116,5,9,0,
		0,115,108,1,0,0,0,115,109,1,0,0,0,115,110,1,0,0,0,115,111,1,0,0,0,115,
		112,1,0,0,0,115,113,1,0,0,0,115,114,1,0,0,0,116,9,1,0,0,0,117,118,5,10,
		0,0,118,119,5,4,0,0,119,120,3,8,4,0,120,11,1,0,0,0,121,122,5,11,0,0,122,
		123,5,4,0,0,123,124,3,8,4,0,124,13,1,0,0,0,125,126,5,12,0,0,126,127,5,
		4,0,0,127,128,3,8,4,0,128,15,1,0,0,0,129,130,5,30,0,0,130,131,5,4,0,0,
		131,132,5,13,0,0,132,17,1,0,0,0,133,134,5,30,0,0,134,135,5,4,0,0,135,136,
		5,14,0,0,136,19,1,0,0,0,137,138,5,30,0,0,138,139,5,4,0,0,139,140,5,15,
		0,0,140,21,1,0,0,0,141,142,5,30,0,0,142,143,5,4,0,0,143,144,5,16,0,0,144,
		23,1,0,0,0,145,146,5,30,0,0,146,147,5,4,0,0,147,148,5,17,0,0,148,25,1,
		0,0,0,149,150,5,18,0,0,150,151,5,4,0,0,151,152,3,8,4,0,152,27,1,0,0,0,
		153,154,5,19,0,0,154,155,5,4,0,0,155,156,3,8,4,0,156,29,1,0,0,0,157,158,
		5,20,0,0,158,159,5,4,0,0,159,160,3,8,4,0,160,31,1,0,0,0,161,162,5,30,0,
		0,162,163,5,4,0,0,163,164,5,21,0,0,164,33,1,0,0,0,165,166,5,30,0,0,166,
		167,5,4,0,0,167,168,5,22,0,0,168,35,1,0,0,0,169,170,5,23,0,0,170,171,5,
		4,0,0,171,172,3,8,4,0,172,37,1,0,0,0,173,174,5,24,0,0,174,175,5,4,0,0,
		175,176,3,8,4,0,176,39,1,0,0,0,177,178,5,25,0,0,178,179,5,4,0,0,179,180,
		3,8,4,0,180,41,1,0,0,0,181,182,5,26,0,0,182,183,5,4,0,0,183,184,3,8,4,
		0,184,43,1,0,0,0,185,186,5,27,0,0,186,187,5,4,0,0,187,188,3,8,4,0,188,
		45,1,0,0,0,189,190,5,28,0,0,190,191,5,4,0,0,191,192,3,8,4,0,192,47,1,0,
		0,0,193,194,5,29,0,0,194,195,5,4,0,0,195,196,3,8,4,0,196,49,1,0,0,0,6,
		59,66,91,99,106,115
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
